# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainV2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainP(object):
    def setupUi(self, MainP):
        MainP.setObjectName("MainP")
        MainP.resize(1800, 1000)
        self.background = QtWidgets.QLabel(MainP)
        self.background.setGeometry(QtCore.QRect(0, 0, 1980, 1100))
        self.background.setStyleSheet("QLabel{\n"
"background-color:rgba(0, 0, 0, 0);\n"
"border-image: url(img/bg02.png);\n"
"}")
        self.background.setText("")
        self.background.setObjectName("background")
        self.label_time_day = QtWidgets.QLabel(MainP)
        self.label_time_day.setGeometry(QtCore.QRect(10, 90, 321, 111))
        self.label_time_day.setStyleSheet("QLabel{\n"
"\n"
"    font: 75 30pt \"微软雅黑\";\n"
"background-color:rgba(0, 0, 0, 0);\n"
"color: white;\n"
"}")
        self.label_time_day.setAlignment(QtCore.Qt.AlignCenter)
        self.label_time_day.setObjectName("label_time_day")
        self.label_time_min = QtWidgets.QLabel(MainP)
        self.label_time_min.setGeometry(QtCore.QRect(30, 10, 281, 101))
        self.label_time_min.setStyleSheet("QLabel{\n"
"    font: 75 40pt \"微软雅黑\";\n"
"background-color:rgba(0, 0, 0, 0);\n"
"color: white;\n"
"font-weight: bold;\n"
"\n"
"}")
        self.label_time_min.setAlignment(QtCore.Qt.AlignCenter)
        self.label_time_min.setObjectName("label_time_min")
        self.label_state = QtWidgets.QLabel(MainP)
        self.label_state.setGeometry(QtCore.QRect(390, 30, 691, 121))
        self.label_state.setStyleSheet("QLabel{\n"
"\n"
"    font: 25 40pt \"微软雅黑\";\n"
"background-color:rgba(0, 0, 0, 0);\n"
"color: white;\n"
"\n"
"\n"
"}")
        self.label_state.setText("")
        self.label_state.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_state.setObjectName("label_state")
        self.label_figure1 = QtWidgets.QLabel(MainP)
        self.label_figure1.setGeometry(QtCore.QRect(770, 60, 351, 61))
        self.label_figure1.setStyleSheet("QLabel{\n"
"font: 70 40pt \"微软雅黑\";\n"
"font-weight: bold;\n"
"background-color:rgba(0, 0, 0, 0);\n"
"color:white;\n"
"}")
        self.label_figure1.setText("")
        self.label_figure1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_figure1.setObjectName("label_figure1")
        self.label_amp1 = QtWidgets.QLabel(MainP)
        self.label_amp1.setGeometry(QtCore.QRect(670, 190, 211, 51))
        self.label_amp1.setStyleSheet("QLabel{\n"
"font: 70 25pt \"微软雅黑\";\n"
"font-weight: bold;\n"
"background-color:rgba(0, 0, 0, 0);\n"
"color:rgb(0,255,255);\n"
"}")
        self.label_amp1.setText("")
        self.label_amp1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_amp1.setObjectName("label_amp1")
        self.label_amp2 = QtWidgets.QLabel(MainP)
        self.label_amp2.setGeometry(QtCore.QRect(1030, 190, 81, 51))
        self.label_amp2.setStyleSheet("QLabel{\n"
"font: 70 25pt \"微软雅黑\";\n"
"color:rgb(0,255,255);\n"
"background-color:rgba(0, 0, 0, 0);\n"
"}")
        self.label_amp2.setText("")
        self.label_amp2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_amp2.setObjectName("label_amp2")
        self.label_amp_disp = QtWidgets.QLabel(MainP)
        self.label_amp_disp.setGeometry(QtCore.QRect(880, 40, 341, 111))
        self.label_amp_disp.setStyleSheet("QLabel{\n"
"font: 70 25pt \"微软雅黑\";\n"
"color:rgb(0,255,255);\n"
"font-weight: bold;\n"
"background-color:rgba(0, 0, 0, 0);\n"
"}")
        self.label_amp_disp.setText("")
        self.label_amp_disp.setAlignment(QtCore.Qt.AlignCenter)
        self.label_amp_disp.setObjectName("label_amp_disp")
        self.button_record = QtWidgets.QPushButton(MainP)
        self.button_record.setGeometry(QtCore.QRect(1280, 720, 451, 91))
        self.button_record.setStyleSheet("QPushButton{\n"
"font: 70 40pt \"微软雅黑\";\n"
"background-color:rgb(30, 150, 30);\n"
"color:white;\n"
"}")
        self.button_record.setObjectName("button_record")
        self.button_exit = QtWidgets.QPushButton(MainP)
        self.button_exit.setGeometry(QtCore.QRect(1280, 860, 451, 91))
        self.button_exit.setStyleSheet("QPushButton{\n"
"font: 70 40pt \"微软雅黑\";\n"
"background-color: rgb(20, 20, 20);\n"
"color:white;\n"
"}")
        self.button_exit.setObjectName("button_exit")
        self.label_figure1_2 = QtWidgets.QLabel(MainP)
        self.label_figure1_2.setGeometry(QtCore.QRect(270, 920, 351, 61))
        self.label_figure1_2.setStyleSheet("QLabel{\n"
"font: 70 23pt \"微软雅黑\";\n"
"font-weight: bold;\n"
"background-color:rgba(0, 0, 0, 0);\n"
"color:white;\n"
"}")
        self.label_figure1_2.setText("")
        self.label_figure1_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_figure1_2.setObjectName("label_figure1_2")
        self.label_figure1_3 = QtWidgets.QLabel(MainP)
        self.label_figure1_3.setGeometry(QtCore.QRect(1100, 930, 151, 71))
        self.label_figure1_3.setStyleSheet("QLabel{\n"
"font: 70 20pt \"微软雅黑\";\n"
"font-weight: bold;\n"
"background-color:rgba(0, 0, 0, 0);\n"
"color:white;\n"
"}")
        self.label_figure1_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_figure1_3.setObjectName("label_figure1_3")
        self.label_state_2 = QtWidgets.QLabel(MainP)
        self.label_state_2.setGeometry(QtCore.QRect(610, 40, 331, 121))
        self.label_state_2.setStyleSheet("QLabel{\n"
"\n"
"    font: 25 40pt \"微软雅黑\";\n"
"background-color:rgba(0, 0, 0, 0);\n"
"color: white;\n"
"\n"
"\n"
"}")
        self.label_state_2.setText("")
        self.label_state_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_state_2.setObjectName("label_state_2")
        self.label_amp1_2 = QtWidgets.QLabel(MainP)
        self.label_amp1_2.setGeometry(QtCore.QRect(0, 410, 111, 151))
        self.label_amp1_2.setStyleSheet("QLabel{\n"
"font: 70 25pt \"微软雅黑\";\n"
"font-weight: bold;\n"
"background-color:rgba(0, 0, 0, 0);\n"
"color:rgb(255,255,0);\n"
"}")
        self.label_amp1_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_amp1_2.setObjectName("label_amp1_2")
        self.label_amp1_3 = QtWidgets.QLabel(MainP)
        self.label_amp1_3.setGeometry(QtCore.QRect(0, 210, 111, 161))
        self.label_amp1_3.setStyleSheet("QLabel{\n"
"font: 70 25pt \"微软雅黑\";\n"
"font-weight: bold;\n"
"background-color:rgba(0, 0, 0, 0);\n"
"color:rgb(230,230,230);\n"
"}")
        self.label_amp1_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_amp1_3.setObjectName("label_amp1_3")
        self.label_amp1_4 = QtWidgets.QLabel(MainP)
        self.label_amp1_4.setGeometry(QtCore.QRect(0, 640, 111, 161))
        self.label_amp1_4.setStyleSheet("QLabel{\n"
"font: 70 25pt \"微软雅黑\";\n"
"font-weight: bold;\n"
"background-color:rgba(0, 0, 0, 0);\n"
"color:rgb(0,255,100);\n"
"}")
        self.label_amp1_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_amp1_4.setObjectName("label_amp1_4")
        self.value_setting = QtWidgets.QLabel(MainP)
        self.value_setting.setGeometry(QtCore.QRect(1660, 720, 111, 91))
        self.value_setting.setStyleSheet("QLabel{\n"
"font: 70 25pt \"微软雅黑\";\n"
"color:rgb(0,255,255);\n"
"font-weight: bold;\n"
"background-color:rgba(0, 0, 0, 0);\n"
"}")
        self.value_setting.setText("")
        self.value_setting.setAlignment(QtCore.Qt.AlignCenter)
        self.value_setting.setObjectName("value_setting")
        self.label_amp1_5 = QtWidgets.QLabel(MainP)
        self.label_amp1_5.setGeometry(QtCore.QRect(1310, 310, 201, 121))
        self.label_amp1_5.setStyleSheet("QLabel{\n"
"font: 70 40pt \"微软雅黑\";\n"
"font-weight: bold;\n"
"background-color:rgba(0, 0, 0, 0);\n"
"color:rgb(200,150,155);\n"
"}<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
"<ui version=\"4.0\">\n"
" <widget name=\"__qt_fake_top_level\">\n"
"  <widget class=\"QLabel\" name=\"label_amp1\">\n"
"   <property name=\"geometry\">\n"
"    <rect>\n"
"     <x>670</x>\n"
"     <y>190</y>\n"
"     <width>211</width>\n"
"     <height>51</height>\n"
"    </rect>\n"
"   </property>\n"
"   <property name=\"styleSheet\">\n"
"    <string notr=\"true\">QLabel{\n"
"font: 70 25pt &quot;微软雅黑&quot;;\n"
"font-weight: bold;\n"
"background-color:rgba(0, 0, 0, 0);\n"
"color:rgb(0,255,255);\n"
"}</string>\n"
"   </property>\n"
"   <property name=\"text\">\n"
"    <string>当前幅度：</string>\n"
"   </property>\n"
"   <property name=\"alignment\">\n"
"    <set>Qt::AlignCenter</set>\n"
"   </property>\n"
"  </widget>\n"
" </widget>\n"
" <resources/>\n"
"</ui>\n"
"")
        self.label_amp1_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_amp1_5.setObjectName("label_amp1_5")
        self.value_b = QtWidgets.QLabel(MainP)
        self.value_b.setGeometry(QtCore.QRect(1470, 320, 231, 111))
        self.value_b.setStyleSheet("QLabel{\n"
"font: 70 40pt \"微软雅黑\";\n"
"font-weight: bold;\n"
"background-color:rgba(0, 0, 0, 0);\n"
"color:rgb(200,150,155);\n"
"}<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
"<ui version=\"4.0\">\n"
" <widget name=\"__qt_fake_top_level\">\n"
"  <widget class=\"QLabel\" name=\"label_amp1\">\n"
"   <property name=\"geometry\">\n"
"    <rect>\n"
"     <x>670</x>\n"
"     <y>190</y>\n"
"     <width>211</width>\n"
"     <height>51</height>\n"
"    </rect>\n"
"   </property>\n"
"   <property name=\"styleSheet\">\n"
"    <string notr=\"true\">QLabel{\n"
"font: 70 25pt &quot;微软雅黑&quot;;\n"
"font-weight: bold;\n"
"background-color:rgba(0, 0, 0, 0);\n"
"color:rgb(0,255,255);\n"
"}</string>\n"
"   </property>\n"
"   <property name=\"text\">\n"
"    <string>当前幅度：</string>\n"
"   </property>\n"
"   <property name=\"alignment\">\n"
"    <set>Qt::AlignCenter</set>\n"
"   </property>\n"
"  </widget>\n"
" </widget>\n"
" <resources/>\n"
"</ui>\n"
"")
        self.value_b.setText("")
        self.value_b.setAlignment(QtCore.Qt.AlignCenter)
        self.value_b.setObjectName("value_b")
        self.value_h = QtWidgets.QLabel(MainP)
        self.value_h.setGeometry(QtCore.QRect(1470, 450, 231, 131))
        self.value_h.setStyleSheet("QLabel{\n"
"font: 70 40pt \"微软雅黑\";\n"
"font-weight: bold;\n"
"background-color:rgba(0, 0, 0, 0);\n"
"color:rgb(255,15,155);\n"
"}<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
"<ui version=\"4.0\">\n"
" <widget name=\"__qt_fake_top_level\">\n"
"  <widget class=\"QLabel\" name=\"label_amp1\">\n"
"   <property name=\"geometry\">\n"
"    <rect>\n"
"     <x>670</x>\n"
"     <y>190</y>\n"
"     <width>211</width>\n"
"     <height>51</height>\n"
"    </rect>\n"
"   </property>\n"
"   <property name=\"styleSheet\">\n"
"    <string notr=\"true\">QLabel{\n"
"font: 70 25pt &quot;微软雅黑&quot;;\n"
"font-weight: bold;\n"
"background-color:rgba(0, 0, 0, 0);\n"
"color:rgb(0,255,255);\n"
"}</string>\n"
"   </property>\n"
"   <property name=\"text\">\n"
"    <string>当前幅度：</string>\n"
"   </property>\n"
"   <property name=\"alignment\">\n"
"    <set>Qt::AlignCenter</set>\n"
"   </property>\n"
"  </widget>\n"
" </widget>\n"
" <resources/>\n"
"</ui>\n"
"")
        self.value_h.setText("")
        self.value_h.setAlignment(QtCore.Qt.AlignCenter)
        self.value_h.setObjectName("value_h")
        self.label_amp1_6 = QtWidgets.QLabel(MainP)
        self.label_amp1_6.setGeometry(QtCore.QRect(1320, 460, 171, 111))
        self.label_amp1_6.setStyleSheet("QLabel{\n"
"font: 70 40pt \"微软雅黑\";\n"
"font-weight: bold;\n"
"background-color:rgba(0, 0, 0, 0);\n"
"color:rgb(230,10,155);\n"
"}<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
"<ui version=\"4.0\">\n"
" <widget name=\"__qt_fake_top_level\">\n"
"  <widget class=\"QLabel\" name=\"label_amp1\">\n"
"   <property name=\"geometry\">\n"
"    <rect>\n"
"     <x>670</x>\n"
"     <y>190</y>\n"
"     <width>211</width>\n"
"     <height>51</height>\n"
"    </rect>\n"
"   </property>\n"
"   <property name=\"styleSheet\">\n"
"    <string notr=\"true\">QLabel{\n"
"font: 70 25pt &quot;微软雅黑&quot;;\n"
"font-weight: bold;\n"
"background-color:rgba(0, 0, 0, 0);\n"
"color:rgb(0,255,255);\n"
"}</string>\n"
"   </property>\n"
"   <property name=\"text\">\n"
"    <string>当前幅度：</string>\n"
"   </property>\n"
"   <property name=\"alignment\">\n"
"    <set>Qt::AlignCenter</set>\n"
"   </property>\n"
"  </widget>\n"
" </widget>\n"
" <resources/>\n"
"</ui>\n"
"")
        self.label_amp1_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_amp1_6.setObjectName("label_amp1_6")
        self.label_amp1_7 = QtWidgets.QLabel(MainP)
        self.label_amp1_7.setGeometry(QtCore.QRect(0, 830, 111, 151))
        self.label_amp1_7.setStyleSheet("QLabel{\n"
"font: 70 25pt \"微软雅黑\";\n"
"font-weight: bold;\n"
"background-color:rgba(0, 0, 0, 0);\n"
"color:rgb(0,100,255);\n"
"}")
        self.label_amp1_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_amp1_7.setObjectName("label_amp1_7")
        self.label_figure1_4 = QtWidgets.QLabel(MainP)
        self.label_figure1_4.setGeometry(QtCore.QRect(1110, 760, 141, 71))
        self.label_figure1_4.setStyleSheet("QLabel{\n"
"font: 70 20pt \"微软雅黑\";\n"
"font-weight: bold;\n"
"background-color:rgba(0, 0, 0, 0);\n"
"color:white;\n"
"}")
        self.label_figure1_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_figure1_4.setObjectName("label_figure1_4")
        self.label_figure1_5 = QtWidgets.QLabel(MainP)
        self.label_figure1_5.setGeometry(QtCore.QRect(70, 600, 141, 101))
        self.label_figure1_5.setStyleSheet("QLabel{\n"
"font: 70 18pt \"微软雅黑\";\n"
"font-weight: bold;\n"
"background-color:rgba(0, 0, 0, 0);\n"
"color:white;\n"
"}")
        self.label_figure1_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_figure1_5.setObjectName("label_figure1_5")
        self.label_figure1_6 = QtWidgets.QLabel(MainP)
        self.label_figure1_6.setGeometry(QtCore.QRect(80, 790, 131, 101))
        self.label_figure1_6.setStyleSheet("QLabel{\n"
"font: 70 18pt \"微软雅黑\";\n"
"font-weight: bold;\n"
"background-color:rgba(0, 0, 0, 0);\n"
"color:white;\n"
"}")
        self.label_figure1_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_figure1_6.setObjectName("label_figure1_6")
        self.value_h_2 = QtWidgets.QLabel(MainP)
        self.value_h_2.setGeometry(QtCore.QRect(1580, 670, 201, 131))
        self.value_h_2.setStyleSheet("QLabel{\n"
"font: 70 40pt \"微软雅黑\";\n"
"font-weight: bold;\n"
"background-color:rgba(0, 0, 0, 0);\n"
"color:rgb(255,15,155);\n"
"}<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
"<ui version=\"4.0\">\n"
" <widget name=\"__qt_fake_top_level\">\n"
"  <widget class=\"QLabel\" name=\"label_amp1\">\n"
"   <property name=\"geometry\">\n"
"    <rect>\n"
"     <x>670</x>\n"
"     <y>190</y>\n"
"     <width>211</width>\n"
"     <height>51</height>\n"
"    </rect>\n"
"   </property>\n"
"   <property name=\"styleSheet\">\n"
"    <string notr=\"true\">QLabel{\n"
"font: 70 25pt &quot;微软雅黑&quot;;\n"
"font-weight: bold;\n"
"background-color:rgba(0, 0, 0, 0);\n"
"color:rgb(0,255,255);\n"
"}</string>\n"
"   </property>\n"
"   <property name=\"text\">\n"
"    <string>当前幅度：</string>\n"
"   </property>\n"
"   <property name=\"alignment\">\n"
"    <set>Qt::AlignCenter</set>\n"
"   </property>\n"
"  </widget>\n"
" </widget>\n"
" <resources/>\n"
"</ui>\n"
"")
        self.value_h_2.setText("")
        self.value_h_2.setAlignment(QtCore.Qt.AlignCenter)
        self.value_h_2.setObjectName("value_h_2")
        self.value_set = QtWidgets.QLabel(MainP)
        self.value_set.setGeometry(QtCore.QRect(950, 0, 201, 131))
        self.value_set.setStyleSheet("QLabel{\n"
"font: 70 20pt \"微软雅黑\";\n"
"font-weight: bold;\n"
"background-color:rgba(0, 0, 0, 0);\n"
"color:rgb(255,15,155);\n"
"}<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
"<ui version=\"4.0\">\n"
" <widget name=\"__qt_fake_top_level\">\n"
"  <widget class=\"QLabel\" name=\"label_amp1\">\n"
"   <property name=\"geometry\">\n"
"    <rect>\n"
"     <x>670</x>\n"
"     <y>190</y>\n"
"     <width>211</width>\n"
"     <height>51</height>\n"
"    </rect>\n"
"   </property>\n"
"   <property name=\"styleSheet\">\n"
"    <string notr=\"true\">QLabel{\n"
"font: 70 25pt &quot;微软雅黑&quot;;\n"
"font-weight: bold;\n"
"background-color:rgba(0, 0, 0, 0);\n"
"color:rgb(0,255,255);\n"
"}</string>\n"
"   </property>\n"
"   <property name=\"text\">\n"
"    <string>当前幅度：</string>\n"
"   </property>\n"
"   <property name=\"alignment\">\n"
"    <set>Qt::AlignCenter</set>\n"
"   </property>\n"
"  </widget>\n"
" </widget>\n"
" <resources/>\n"
"</ui>\n"
"")
        self.value_set.setText("")
        self.value_set.setAlignment(QtCore.Qt.AlignCenter)
        self.value_set.setObjectName("value_set")
        self.background.raise_()
        self.label_time_day.raise_()
        self.label_time_min.raise_()
        self.label_state.raise_()
        self.button_record.raise_()
        self.button_exit.raise_()
        self.label_figure1.raise_()
        self.label_amp2.raise_()
        self.label_amp1.raise_()
        self.label_amp_disp.raise_()
        self.label_figure1_2.raise_()
        self.label_state_2.raise_()
        self.label_amp1_2.raise_()
        self.label_amp1_3.raise_()
        self.label_figure1_3.raise_()
        self.label_amp1_4.raise_()
        self.value_setting.raise_()
        self.label_amp1_5.raise_()
        self.value_b.raise_()
        self.value_h.raise_()
        self.label_amp1_6.raise_()
        self.label_amp1_7.raise_()
        self.label_figure1_4.raise_()
        self.label_figure1_5.raise_()
        self.label_figure1_6.raise_()
        self.value_h_2.raise_()
        self.value_set.raise_()

        self.retranslateUi(MainP)
        QtCore.QMetaObject.connectSlotsByName(MainP)

    def retranslateUi(self, MainP):
        _translate = QtCore.QCoreApplication.translate
        MainP.setWindowTitle(_translate("MainP", "Dialog"))
        self.label_time_day.setText(_translate("MainP", "2021/7/22"))
        self.label_time_min.setText(_translate("MainP", "10:30"))
        self.button_record.setText(_translate("MainP", "开始记录数据"))
        self.button_exit.setText(_translate("MainP", "退出演示"))
        self.label_figure1_3.setText(_translate("MainP", "时间/s"))
        self.label_amp1_2.setText(_translate("MainP", "<html><head/><body><p>呼吸2</p><p>曲线</p></body></html>"))
        self.label_amp1_3.setText(_translate("MainP", "<html><head/><body><p>呼吸1</p><p>曲线</p></body></html>"))
        self.label_amp1_4.setText(_translate("MainP", "<html><head/><body><p>呼吸</p><p>记录</p></body></html>"))
        self.label_amp1_5.setText(_translate("MainP", "呼吸："))
        self.label_amp1_6.setText(_translate("MainP", "心率："))
        self.label_amp1_7.setText(_translate("MainP", "<html><head/><body><p>心率</p><p>记录</p></body></html>"))
        self.label_figure1_4.setText(_translate("MainP", "时间/s"))
        self.label_figure1_5.setText(_translate("MainP", "bpm"))
        self.label_figure1_6.setText(_translate("MainP", "bpm"))
